baseURL = 'http://sjiang20.github.io/'
languageCode = 'en-us'
title = 'My Simple Dev Blog'
theme = 'smol'


# Parameters
[params]
    subtitle = "Serena Jiang"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/sjiang20"
        weight = 1

    [[menu.footer]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/jiang1028/"
        weight = 2

    [[menu.footer]]
        name = "Subcribe"
        url = "/imprint"
        weight = 3
